Updated getting started pages
LinkStackOrg/docs pull request #6
Opened 2023-12-13 21:28 UTC by avoidthehack

Edits for requirements, set up, and the Edit Terms, Privacy, and Contact pages.

2023-12-15 20:49 UTC, MagicLike requested changes

2023-12-15 20:49 UTC, MagicLike commented on docs/getting-started/requirements.md
> +**Under most conditions, LinkStack conditions is a simple drag and drop solution with no further configuration required.**
```suggestion
**Under most conditions, LinkStack is a simple drag and drop solution with no further configuration required.**
```

2023-12-15 20:49 UTC, MagicLike commented on docs/setup/access-admin
Wouldn't it be better to include this one in the FAQ instead of creating a new page?

2023-12-18 16:04 UTC, avoidthehack commented on docs/setup/access-admin
Perhaps, seeing as it is a legitimate FAQ I saw asked by other users. My only concern is that it may be "buried" in the FAQ. I created a new page as I assumed most people wouldn't be looking for the admin page until they finished the getting started section.

2023-12-21 23:06 UTC, MagicLike commented on docs/setup/access-admin
For this purpose there is the search function on the docs page, so users can quickly find the desired solution.
Another option would be to first add it into the FAQ and then link it at the bottom of the Getting started page... What do you think?

2024-01-04 16:24 UTC, avoidthehack commented on docs/setup/access-admin
Hey, sorry holidays took me away from the world for a bit there.

I think that's a great solution, not at all opposed as it still highlights it for users looking for it.

2024-08-20 19:10 UTC, closed without merging